ID: 806761

Name: Jiayu Guan

constrained_min.py

In [234]:
import numpy as np

In [239]:
from unconstrained_min import *

def interior_pt(func, x0, ineq_constraints, eq_constraints_mat, eq_constraints_rhs):

    #barrier function
    def barrier_func(x):
        barrier = t * (x[0]**2 + x[1]**2 + (x[2] + 1)**2) - np.log(np.maximum(epsilon,-x[0])) - np.log(np.maximum(epsilon,-x[1]))- np.log(np.maximum(epsilon,-x[2]))
        return barrier
    
    #lagrangian
    def lagrangian_func(x):
        lf = t * (x[0]**2 + x[1]**2 + (x[2] + 1)**2) - np.log(np.maximum(epsilon,-x[0])) - np.log(np.maximum(epsilon,-x[1]))- np.log(np.maximum(epsilon,-x[2])) + 1*(x[0]+x[1]+x[2]-1)
        return lf

    t = 1.0
    mu = 10
    epsilon = 0.001

    path=[]
    path.append(x0)
    x = x0

    while True:
        xstar, func_v, flag, path_new = newton(lagrangian_func,x)
        x = xstar
        path.append(xstar)
        if len(ineq_constraints)/t < epsilon:
            ystar = func(xstar)
            return xstar, ystar, path
        t = mu * t

# example1

In [240]:
def ex1(x):
    return x[0]**2 + x[1]**2 + (x[2] + 1)**2

def ineq_constraints1(x):
    return x[0]

def ineq_constraints2(x):
    return x[1]

def ineq_constraints3(x):
    return x[2]

ineq_constraints = [ineq_constraints1, ineq_constraints2, ineq_constraints3]
eq_constraints_mat = np.array([[1, 1, 1]])
eq_constraints_rhs = np.array([1])

In [241]:
def test_qp():
    x0 = np.array([0.1, 0.2, 0.7])
    return interior_pt(ex1, x0, ineq_constraints, eq_constraints_mat, eq_constraints_rhs)

In [242]:
test_qp()

For newton method, the iteration is 1 the current location is [-0.51402344 -0.51239939 -1.51511636] and the current objective value is -1.8307760336231191
For newton method, the iteration is 2 the current location is [-0.84556699 -0.8443069  -1.7739231 ] and the current objective value is -2.673208775283595
For newton method, the iteration is 3 the current location is [-0.99038801 -0.99024393 -1.78063134] and the current objective value is -2.7479320710171753
For newton method, the iteration is 4 the current location is [-0.99994849 -1.00010143 -1.78082504] and the current objective value is -2.7482140400352604
For newton method, the iteration is 5 the current location is [-0.99997331 -1.00010141 -1.78079287] and the current objective value is -2.748214045375437
For newton method, the iteration is 6 the current location is [-1.00004911 -1.00002565 -1.78079287] and the current objective value is -2.748214057265836
For newton method, the iteration is 1 the current location is [-0.1432886

(array([-0.00709611, -0.00709611, -1.00010012]),
 0.00010071949517331408,
 [array([0.1, 0.2, 0.7]),
  array([-1.00004911, -1.00002565, -1.78079287]),
  array([-0.24999773, -0.25000265, -1.09565219]),
  array([-0.07325426, -0.07325413, -1.00995112]),
  array([-0.02261201, -0.02261201, -1.00099972]),
  array([-0.00709611, -0.00709611, -1.00010012])])

In [102]:
def interior_pt(func):

    #barrier function
    def barrier_func(x):
        barrier = func(x) + x[0] **2
        return barrier
    return barrier_func

In [103]:
def test1(x):
    return x[0]+x[1]

In [105]:
interior_pt(test1)([2,1])

7

# example2

In [243]:
def interior_pt2(func, x0, ineq_constraints, eq_constraints_mat, eq_constraints_rhs):

    #lagrangian
    def lagrangian_func(x):
        lf = t * (-x[0]-x[1]) - np.log(np.maximum(epsilon,-(x[1]-1))) - np.log(np.maximum(epsilon,-(x[0]-2)))- np.log(np.maximum(epsilon,-(-x[0]-x[1]+1)))- np.log(np.maximum(epsilon,x[1]))
        return lf

    t = 1.0
    mu = 10
    epsilon = 0.01

    path=[]
    path.append(x0)
    x = x0

    while True:
        xstar, func_v, flag, path_new = newton(lagrangian_func,x)
        path.append(xstar)
        x = xstar
        if len(ineq_constraints)/t < epsilon:
            ystar = func(xstar)
            return xstar, ystar, path
        else:
            t = mu * t

In [244]:
def ex2(x):
    return -x[0]-x[1]

def ineq_constraints1(x):
    return x[0]-2

def ineq_constraints2(x):
    return -x[1]

def ineq_constraints3(x):
    return x[1]-1

def ineq_constraints4(x):
    return -x[0]-x[1]+1

ineq_constraints = [ineq_constraints1, ineq_constraints2, ineq_constraints3, ineq_constraints4]
eq_constraints_mat = None
eq_constraints_rhs = None

In [245]:
def test_lp():
    x0 = np.array([0.5, 0.75])
    return interior_pt2(ex2, x0, ineq_constraints, eq_constraints_mat, eq_constraints_rhs)

In [246]:
test_lp()

For newton method, the iteration is 1 the current location is [0.86415288 0.64659655] and the current objective value is 0.5099256883650283
For newton method, the iteration is 2 the current location is [1.31895504 0.64178529] and the current objective value is -0.0664380663359786
For newton method, the iteration is 3 the current location is [1.47679971 0.69809413] and the current objective value is -0.1312393824439912
For newton method, the iteration is 4 the current location is [1.46329191 0.69673854] and the current objective value is -0.1316707766428688
For newton method, the iteration is 5 the current location is [1.46302603 0.69675299] and the current objective value is -0.13167093599063245
For newton method, the iteration is 6 the current location is [1.46302062 0.69673466] and the current objective value is -0.1316709371446041
For newton method, the iteration is 7 the current location is [1.46301914 0.69674305] and the current objective value is -0.13167093732411422
For newton m

(array([3.49998528, 1.24369012]),
 -4.743675400386778,
 [array([0.5 , 0.75]),
  array([1.46301914, 0.69674305]),
  array([3.49998528, 1.24369012]),
  array([3.49998528, 1.24369012]),
  array([3.49998528, 1.24369012])])